# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social App
  pod 'Alamofire', '~> 5.4'
  pod 'RealmSwift', '~> 10.3'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'

end
